<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Оргтехника
    </h1>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "equipment/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group pl-0 col-12">
    <div class="input-group col-12">
        <?php echo $this->tag->textField(["type", "size" => 30, "class" => "form-control", "id" => "fieldType", "placeholder" => "Введите тип"]) ?>
        <div class="input-group-append">
            <a class="btn btn-info" href="#advancedSearch" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="comment">Расширенный поиск</a>
        </div>
        <?php echo $this->tag->submitButton(["Найти", "class" => "btn btn-default d-inline"]) ?>
    </div>
</div>

<!-- begin advanced search -->
<div class="collapse multi-collapse pl-3" id="advancedSearch" style="max-height: 50vh; overflow-x: hidden; overflow-y: auto;">

<div class="form-group">
    <label for="fieldManufacturer" class="col-sm-2 control-label">Производитель</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["manufacturer", "size" => 30, "class" => "form-control", "id" => "fieldManufacturer"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSpecifications" class="col-sm-2 control-label">Характеристики</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["specifications", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldSpecifications"]) ?>
    </div>
</div>

</div> <!-- end advanced search -->

<?php echo $this->tag->endForm(); ?>

<?php if (isset($page)) { 
    $this->partial("equipment/pagination", [ 'page' => $page ]);
}?>
