<style>
    .hidden{
        display:none;
        visibility:hidden;
    }
</style>
<div class="row px-3">
    <table class="table table-bordered table-striped table-hover" id="paginationTable">
        <thead class="thead-dark">
            <tr>
                <th class='hidden'></th>
                <th scope="col"><p class="text-center m-0">Тип оргтехники</p></th>
                <th scope="col"><p class="text-center m-0">Производитель</p></th>
                <th scope="col"><p class="text-center m-0">Характеристики</p></th>

                <th scope="col"><p class="text-center m-0">Действия</p></th>
                <!-- <th scope="col"></th> -->
            </tr>
        </thead>
        <tbody>
        <?php if (isset($page)): 
            foreach ($page->items as $equipment): ?>
            <tr>
                <td class='hidden'><?php echo $equipment->getEquipmentId() ?></td>
                <td><?php echo nl2br($equipment->getType()) ?></td>
                <td><?php echo nl2br($equipment->getManufacturer()) ?></td>
                <td><?php echo nl2br($equipment->getSpecifications()) ?></td>

                <td>
                    <?php echo $this->tag->linkTo(["equipment/edit/" . $equipment->getEquipmentId(), '<i class="fas fa-edit d-inline"></i> Изменить', 'class' => 'btn btn-success w-100']); ?>
                    <?php echo $this->tag->linkTo(["equipment/delete/" . $equipment->getEquipmentId(), '<i class="fas fa-trash d-inline"></i> Удалить', 'class' => 'btn btn-danger w-100']); ?>
                </td>
            </tr>
        <?php endforeach; endif; ?>
        </tbody>
    </table>
</div>
<?php if (isset($page)): ?>
<div class="d-flex justify-content-center px-3">
    <? echo CustomTags::pagination([
        'link' => 'equipment/search?page=%d',
        'current' => $page->current,
        'next' => $page->next,
        'before' => $page->before,
        'count'   => $page->total_pages,
    ]);
    ?>
</div>
<?php endif; ?>

<? echo Phalcon\Tag::javascriptInclude("js/pagination.js") ?>
