<style>
    .hidden{
        display:none;
        visibility:hidden;
    }
</style>
<div class="row px-3">
    <table class="table table-bordered table-striped table-hover" id="paginationTable">
        <thead class="thead-dark">
            <tr>
                <th class='hidden'></th>
                <th>Местоположение</th>
                <th>Инвентарный номер</th>
                <th>Название</th>
                <th>Количество</th>
                <th>Дата ввода в эксплуатацию</th>
            </tr>
        </thead>
        <tbody>
        <?php if (isset($page)):
            foreach ($page->items as $material_value): ?>
            <tr>
                <td class='hidden'><?php echo $material_value->getMaterialValueId() ?></td>
                <td><?php echo nl2br($material_value->getLocationName()) ?></td>
                <td><?php echo nl2br($material_value->getInventoryNum()) ?></td>
                <td><?php echo nl2br($material_value->getName()) ?></td>
                <td><?php echo nl2br($material_value->getCount()) ?></td>
                <td><?php echo nl2br($material_value->getEnterDate()) ?></td>
            </tr>
        <?php endforeach; endif; ?>
        </tbody>
    </table>
</div>
<?php if (isset($page)): ?>
<div class="d-flex justify-content-center px-3">
    <? echo CustomTags::pagination([
        'link' => 'report/forecast?page=%d',
        'current' => $page->current,
        'next' => $page->next,
        'before' => $page->before,
        'count'   => $page->total_pages,
    ]);
    ?>
</div>
<?php endif; ?>