<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<? echo Phalcon\Tag::javascriptInclude('js/bootstrap-filestyle.min.js'); ?>
<? echo Phalcon\Tag::javascriptInclude('js/material_type.js'); ?>
<? echo Phalcon\Tag::stylesheetLink('css/form.css'); ?>
<div class="row">
    <nav>
        <ul class="pager">
        <?php echo $this->tag->linkTo(["material_value", '<i class="fas fa-arrow-left"></i><span class="font-weight-bold"> Вернуться</span>', 'class' => 'btn btn-success']) ?>
        <?php echo $this->tag->linkTo(["material_value/qr/" . $material_value_id, 'Сгенерировать QR-код', 'class' => 'btn btn-info']) ?>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Изменить
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "material_value/save",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data",
            "method" => "post"
        ]
    );
?>

<div class="row">
    <div class="col-7">

        <div class="form-group required">
            <label for="fieldLocationLocationId" class="col-12 control-label">Местоположение</label>
            <div class="col-12">
                <? echo Phalcon\Tag::select(
                    [
                        'location_location_id',
                        Location::getAllByFullname(),
                        'using'      => [
                            'location_id',
                            'fullname',
                        ],
                        'useEmpty'   => true,
                        'emptyText'  => 'Выберите один из вариантов',
                        'emptyValue' => '@',
                        'class' => 'form-control',
                        'id' => 'fieldLocationLocationId',
                    ]
                );
                ?>
            </div>
        </div>

        <div class="form-group required">
            <label for="fieldType" class="col-12 control-label">Тип ценности</label>
            <div class="col-12">
                <? echo Phalcon\Tag::selectStatic(
                    [
                        'type',
                        MaterialValue::getAllTypes(),
                        'useEmpty'   => true,
                        'emptyText'  => 'Выберите один из вариантов',
                        'emptyValue' => '@',
                        'class' => 'form-control',
                        'id' => 'fieldType',
                        'disabled' => 'true'
                    ]
                );
                ?>
            </div>
        </div>

        <div class="form-group">
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="fieldInventoryNum required" class="col-12 control-label">Инвентарный номер</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["inventory_num", "size" => 30, "class" => "form-control", "id" => "fieldInventoryNum"]) ?>
                    </div>
                </div>
                <div class="form-group col-6">
                    <label for="fieldSerialNum" class="col-12 control-label">Серийный номер</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["serial_num", "size" => 30, "class" => "form-control", "id" => "fieldSerialNum"]) ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group required">
            <label for="fieldName" class="col-12 control-label">Название</label>
            <div class="col-12">
                <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
            </div>
        </div>

        <div class="form-group">
            <label for="fieldDescription" class="col-12 control-label">Описание</label>
            <div class="col-12">
                <?php echo $this->tag->textArea(["description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescription"]) ?>
            </div>
        </div>

        <div class="form-group">
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="fieldPrice" class="col-12 control-label">Цена</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
                    </div>
                </div>
                <div class="form-group col-6 required">
                    <label for="fieldCount" class="col-12 control-label">Количество</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["count", "type" => "number", "class" => "form-control", "id" => "fieldCount"]) ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="fieldEnterDate required" class="col-12 control-label">Дата ввода в эксплуатацию</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["enter_date", "type" => "date", "class" => "form-control", "id" => "fieldEnterDate"]) ?>
                    </div>
                </div>
                <div class="form-group col-6">
                    <label for="fieldExitDate" class="col-12 control-label">Дата списания</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["exit_date", "type" => "date", "class" => "form-control", "id" => "fieldExitDate"]) ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="fieldPhoto" class="col-12 control-label">Фото</label>
            <div class="col-12">
                <input id="fieldPhoto" name="photo" type="file">
            </div>
        </div>

        <? if (isset($photo)) { echo Phalcon\Tag::image(['files/photo/'.$photo, 'style' => 'max-height: 30vh;', 'class' => 'p-3']); }?>

    </div>
    <div class="col-5">
        <h4 id="furnitureLabel">Мебель</h4>
        <div class="form-group required" id="fieldFurnitureBlock">
            <label for="fieldFurnitureSpecification" class="col-12 control-label">Характеристики</label>
            <div class="col-12">
                <?php echo $this->tag->textArea(["furniture_specification", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldFurnitureSpecification"]) ?>
            </div>
        </div>
        <h4 id="equipmentLabel">Оргтехника</h4>
        <div class="form-group required" id="fieldEquipmentTypeBlock">
            <label for="fieldEquipmentType" class="col-12 control-label">Тип оргтехники</label>
            <div class="col-12">
                <?php echo $this->tag->textField(["equipment_type", "size" => 30, "class" => "form-control", "id" => "fieldEquipmentType"]) ?>
            </div>
        </div>

        <div class="form-group required" id="fieldEquipmentManufacturerBlock">
            <label for="fieldEquipmentManufacturer" class="col-12 control-label">Производитель</label>
            <div class="col-12">
                <?php echo $this->tag->textField(["equipment_manufacturer", "size" => 30, "class" => "form-control", "id" => "fieldEquipmentManufacturer"]) ?>
            </div>
        </div>

        <div class="form-group required" id="fieldEquipmentSpecificationBlock">
            <label for="fieldEquipmentSpecification" class="col-12 control-label">Характеристики</label>
            <div class="col-12">
                <?php echo $this->tag->textArea(["equipment_specification", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldEquipmentSpecification"]) ?>
            </div>
        </div>
        <div class="col-12 my-3">
            <?php echo $this->tag->linkTo(["material_value/licenses/" . $material_value_id, '<span class="font-weight-bold">Управление лицензиями</span>', 'class' => 'btn btn-success', 'id' => 'btnLicenseSetup']) ?>
        </div>
        <div class="col-12 my-3">
            <?php echo $this->tag->linkTo(["material_value/specifications/" . $material_value_id, '<span class="font-weight-bold">Управление характеристиками</span>', 'class' => 'btn btn-success', 'id' => 'btnSpecificationSetup']) ?>
        </div>
    </div>
</div>

<?php echo $this->tag->hiddenField("material_value_id") ?>
<?php echo $this->tag->hiddenField("type") ?>

<div class="form-group">
    <div class="col-12">
        <?php echo $this->tag->submitButton(["Обновить", "class" => "btn btn-success"]) ?>
        <?php echo $this->tag->linkTo(["material_value/delete/" . $material_value_id, '<i class="fas fa-trash d-inline"></i> Удалить', 'class' => 'btn btn-danger']); ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<script>
    $(function() {
        $('#fieldExitDate').datepicker({
            uiLibrary: 'bootstrap4',
            locale: 'ru-ru'
        });
        $('#fieldEnterDate').datepicker({
            uiLibrary: 'bootstrap4',
            locale: 'ru-ru'
        });
        $(":file").filestyle({
            placeholder: "Файл не выбран",
            dragdrop: false,
            htmlIcon: '<i class="fas fa-lg fa-file-upload"></i>',
            text: "Выберите файл",
            btnClass: "btn-primary",
        });
        $('#myList > a').on('click', function () {
            $("#myList > a").removeClass("active");
            $(this).addClass("active");
        });
    });
</script>
