<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Материальные ценности
    </h1>
    <p>
    <?php echo $this->tag->linkTo(["material_value/new", '<i class="fas fa-plus"></i><span class="font-weight-bold"> Добавить</span>', 'class' => 'btn btn-success']) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "material_value/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldMaterialValueId" class="col-sm-2 control-label">Material Of Value</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["material_value_id", "type" => "number", "class" => "form-control", "id" => "fieldMaterialValueId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["type", [], "class" => "form-control", "id" => "fieldType"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldInventoryNum" class="col-sm-2 control-label">Inventory Of Num</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["inventory_num", "size" => 30, "class" => "form-control", "id" => "fieldInventoryNum"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSerialNum" class="col-sm-2 control-label">Serial Of Num</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["serial_num", "size" => 30, "class" => "form-control", "id" => "fieldSerialNum"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCount" class="col-sm-2 control-label">Count</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["count", "type" => "number", "class" => "form-control", "id" => "fieldCount"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEnterDate" class="col-sm-2 control-label">Enter Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["enter_date", "type" => "date", "class" => "form-control", "id" => "fieldEnterDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldExitDate" class="col-sm-2 control-label">Exit Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["exit_date", "type" => "date", "class" => "form-control", "id" => "fieldExitDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhoto" class="col-sm-2 control-label">Photo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["photo", "size" => 30, "class" => "form-control", "id" => "fieldPhoto"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLocationLocationId" class="col-sm-2 control-label">Location Of Location</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["location_location_id", "type" => "number", "class" => "form-control", "id" => "fieldLocationLocationId"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
