<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Лицензии на ПО
    </h1>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "material_value/search_licenses",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group pl-0 col-12">
    <div class="input-group col-12">
    <?php echo $this->tag->textField(["po_name", "size" => 30, "class" => "form-control", "id" => "fieldPoName", "placeholder" => "Введите название ПО"]) ?>
        <div class="input-group-append">
            <a class="btn btn-info" href="#advancedSearch" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="comment">Расширенный поиск</a>
        </div>
        <?php echo $this->tag->submitButton(["Найти", "class" => "btn btn-default d-inline"]) ?>
    </div>
</div>

<!-- begin advanced search -->
<div class="collapse multi-collapse pl-3" id="advancedSearch" style="max-height: 50vh; overflow-x: hidden; overflow-y: auto;">

<div class="form-group">
    <div class="form-row">
        <div class="form-group col-6">
            <label for="fieldPoVersion" class="control-label">Версия ПО</label>
            <div class="">
                <?php echo $this->tag->textField(["po_version", "size" => 30, "class" => "form-control", "id" => "fieldPoVersion"]) ?>
            </div>
        </div>
        <div class="form-group col-6">
            <label for="fieldLicenseNumber" class="control-label">Номер лицензии</label>
            <div class="">
                <?php echo $this->tag->textField(["license_number", "size" => 30, "class" => "form-control", "id" => "fieldLicenseNumber"]) ?>
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    <div class="form-row">
        <div class="form-group col-6">
            <label for="fieldEndDateBegin" class="col-12 control-label">Дата окончания лицензии - начало</label>
            <div class="">
                <?php echo $this->tag->textField(["end_date_begin", "type" => "date", "class" => "form-control", "id" => "fieldEndDateBegin"]) ?>
            </div>
        </div>
        <div class="form-group col-6">
            <label for="fieldEndDateEnd" class="col-12 control-label">Дата окончания лицензии - конец</label>
            <div class="">
                <?php echo $this->tag->textField(["end_date_end", "type" => "date", "class" => "form-control", "id" => "fieldEndDateEnd"]) ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->tag->hiddenField("material_value_id") ?>
</div> <!-- end advanced search -->

<?php echo $this->tag->endForm(); ?>

<?php if (isset($page)) { 
    $this->partial("material_value/licenses_pagination", [ 'page' => $page, 'material_value_id' => $material_value_id ]);
}?>

<script>
    var id = "<? echo $material_value_id; ?>";
    $('input[name="material_value_id"]').val(id);
    $(function() {
        $('#fieldEndDateBegin').datepicker({
            uiLibrary: 'bootstrap4',
            locale: 'ru-ru'
        });
        $('#fieldEndDateEnd').datepicker({
            uiLibrary: 'bootstrap4',
            locale: 'ru-ru'
        });
    });
</script>