<style>
.hidden{
    display:none;
    visibility:hidden;
}
</style>
<div class="row px-3">
    <table class="table table-bordered table-striped table-hover" id="paginationTable">
        <thead class="thead-dark">
            <tr>
                <th class='hidden'></th>
                <th>Название ПО</th>
                <th>Версия ПО</th>
                <th>Номер лицензии</th>
                <th>Дата окончания</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
        <? if (isset($page)):
            $equipment_id = MaterialValue::findById($material_value_id)->getEquipmentEquipmentId();
            foreach ($page as $license): ?>
            <tr>
                <td class='hidden'><? echo $license->getLicenseId() ?></td>
                <td><? echo nl2br($license->getPoName()) ?></td>
                <td><? echo nl2br($license->getPoVersion()) ?></td>
                <td><? echo nl2br($license->getLicenseNumber()) ?></td>
                <td><? echo nl2br($license->getEndDate()) ?></td>
                <td class='actions'>
                    <?  $license_id = $license->getLicenseId();
                        $equipment_id = Equipment::findById($equipment_id)->getEquipmentId();
                        $found_license = License::findFirst([[
                            'equipment_ids' => $equipment_id
                        ]]);
                        if ($found_license) { ?>
                            <button class='btn btn-danger w-100 lic-rem' name='<? echo $license_id; ?>'><i class="fas fa-edit d-inline"></i> Убрать лицензию</button>
                        <? } else { ?>
                            <button class='btn btn-success w-100 lic-add' name='<? echo $license_id; ?>'><i class="fas fa-edit d-inline"></i> Добавить лицензию</button>
                        <? } ?>
                </td>
            </tr>
        <? endforeach; endif; ?>
        </tbody>
    </table>
</div>

<script>
    var material_id = "<? echo $material_value_id ?>";
    var staticUri = "<? echo ($this->config->application->staticUri ?? '') ?>";
    $(document).ready(function() {
        // Добавление лицензии
        $("td.actions").on('click', 'button.lic-add', function() {
            $element = $(this);
            $.ajax({
                url: staticUri + 'material_value/add_license/' + material_id + '/' + $(this).attr('name'),
                success: function(message) {
                    changeButton($element);
                    console.log(message);
                },
                error:function() {
                    alert('Ошибка при отправке ajax запроса');
                    console.log("lic-add ajax error");
                }
            });
        });
        // Удаление лицензии
        $("td.actions").on('click', 'button.lic-rem', function() {
            $element = $(this);
            $.ajax({
                url: staticUri + 'material_value/rem_license/' + material_id + '/' + $(this).attr('name'),
                success: function(message) {
                    changeButton($element);
                    console.log(message);
                },
                error: function(message) {
                    alert('Ошибка при отправке ajax запроса');
                    console.log("lic-rem ajax error");
                }
            });
        });
        // Меняем кнопку
        function changeButton(elem) {
            if (elem.hasClass('lic-add')) {
                elem.html('<i class="fas fa-edit d-inline"></i> Убрать лицензию');
            } else if (elem.hasClass('lic-rem')) {
                elem.html('<i class="fas fa-edit d-inline"></i> Добавить лицензию');
            }
            elem.toggleClass('lic-add lic-rem btn-success btn-danger');
        }
    });
</script>