<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<? echo Phalcon\Tag::javascriptInclude('js/bootstrap-filestyle.min.js'); ?>

<div class="row">
    <nav>
        <ul class="pager">
            <?php echo $this->tag->linkTo(["material_value", '<i class="fas fa-arrow-left"></i><span class="font-weight-bold"> Вернуться</span>', 'class' => 'btn btn-success']) ?>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Добавить материальную ценность
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "material_value/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data",
            "method" => "post"
        ]
    );
?>

<div class="form-group">
    <label for="fieldLocationLocationId" class="col-sm-2 control-label">Местоположение</label>
    <div class="col-sm-10">
        <? echo Phalcon\Tag::select(
            [
                'location_location_id',
                Location::getAllByFullname(),
                'using'      => [
                    'location_id',
                    'fullname',
                ],
                'useEmpty'   => true,
                'emptyText'  => 'Выберите один из вариантов',
                'emptyValue' => '@',
                'class' => 'form-control',
                'id' => 'fieldLocationLocationId',
            ]
        );
        ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Тип ценности</label>
    <div class="col-sm-10">
        <? echo Phalcon\Tag::selectStatic(
            [
                'type',
                MaterialValue::getAllTypes(),
                'useEmpty'   => true,
                'emptyText'  => 'Выберите один из вариантов',
                'emptyValue' => '@',
                'class' => 'form-control',
                'id' => 'fieldType',
            ]
        );
        ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldInventoryNum" class="col-sm-2 control-label">Инвентарный номер</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["inventory_num", "size" => 30, "class" => "form-control", "id" => "fieldInventoryNum"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSerialNum" class="col-sm-2 control-label">Серийный номер</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["serial_num", "size" => 30, "class" => "form-control", "id" => "fieldSerialNum"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Название</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Описание</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Цена</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCount" class="col-sm-2 control-label">Количество</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["count", "type" => "number", "class" => "form-control", "id" => "fieldCount"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEnterDate" class="col-sm-2 control-label">Дата ввода в эксплуатацию</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["enter_date", "type" => "date", "class" => "form-control", "id" => "fieldEnterDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldExitDate" class="col-sm-2 control-label">Дата списания</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["exit_date", "type" => "date", "class" => "form-control", "id" => "fieldExitDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhoto" class="col-sm-2 control-label">Фото</label>
    <div class="col-sm-10">
        <input id="fieldPhoto" name="photo" type="file">
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Добавить", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<script>
    $('#fieldExitDate').datepicker({
        uiLibrary: 'bootstrap4',
        locale: 'ru-ru'
    });
    $('#fieldEnterDate').datepicker({
        uiLibrary: 'bootstrap4',
        locale: 'ru-ru'
    });
    $(":file").filestyle({
        placeholder: "Файл не выбран",
        dragdrop: false,
        htmlIcon: '<i class="fas fa-lg fa-file-upload"></i>',
        text: "Выберите файл",
        btnClass: "btn-primary",
    });
</script>
