<div class="row px-3">
    <table class="table table-bordered table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="hidden"></th>
                <th scope="col"><p class="text-center m-0">Местоположение</p></th>
                <th scope="col"><p class="text-center m-0">Тип ценности</p></th>
                <th scope="col"><p class="text-center m-0">Инвентарный номер</p></th>
                <th scope="col"><p class="text-center m-0">Серийный номер</p></th>
                <th scope="col"><p class="text-center m-0">Название</p></th>
                <th scope="col"><p class="text-center m-0">Описание</p></th>
                <th scope="col"><p class="text-center m-0">Цена</p></th>
                <th scope="col"><p class="text-center m-0">Количество</p></th>
                <th scope="col"><p class="text-center m-0">Дата ввода в эксплуатацию</p></th>
                <th scope="col"><p class="text-center m-0">Дата списания</p></th>
                <th scope="col"><p class="text-center m-0">Фото</p></th>

                <th scope="col"><p class="text-center m-0">Действия</p></th>
                <!-- <th scope="col"></th> -->
            </tr>
        </thead>
        <tbody>
        <?php if (isset($page)): 
            foreach ($page->items as $material_value): ?>
            <tr>
                <td scope="hidden"><?php echo $material_value->getMaterialValueId() ?></td>
                <td><?php echo $material_value->getLocationName() ?></td>
                <td><?php echo $material_value->getTypeName() ?></td>
                <td><?php echo $material_value->getInventoryNum() ?></td>
                <td><?php echo $material_value->getSerialNum() ?></td>
                <td><?php echo $material_value->getName() ?></td>
                <td><?php echo $material_value->getDescription() ?></td>
                <td><?php echo $material_value->getPrice() ?></td>
                <td><?php echo $material_value->getCount() ?></td>
                <td><?php echo $material_value->getEnterDate() ?></td>
                <td><?php echo $material_value->getExitDate() ?></td>
                <td><?php echo $material_value->getPhoto() ?></td>            

                <td>
                    <?php echo $this->tag->linkTo(["material_value/edit/" . $material_value->getMaterialValueId(), '<i class="fas fa-edit d-inline"></i> Изменить', 'class' => 'btn btn-success w-100']); ?>
                <!-- </td>
                <td> -->
                    <?php echo $this->tag->linkTo(["material_value/delete/" . $material_value->getMaterialValueId(), '<i class="fas fa-trash d-inline"></i> Удалить', 'class' => 'btn btn-danger w-100']); ?>
                </td>
            </tr>
        <?php endforeach; endif; ?>
        </tbody>
    </table>
</div>
<?php if (isset($page)): ?>
<div class="d-flex justify-content-center px-3">
    <? echo CustomTags::pagination([
        'link' => 'material_value/search?page=%d',
        'current' => $page->current,
        'next' => $page->next,
        'before' => $page->before,
        'count'   => $page->total_pages,
    ]);
    ?>
</div>
<?php endif; ?>