<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <?php echo $this->tag->linkTo(["material_value", '<i class="fas fa-arrow-left"></i><span class="font-weight-bold"> Вернуться</span>', 'class' => 'btn btn-success']) ?>
            <?php echo $this->tag->linkTo(["material_value/new", '<i class="fas fa-plus"></i><span class="font-weight-bold"> Добавить</span>', 'class' => 'btn btn-success']) ?>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Местоположение</th>
                <th>Тип ценности</th>
                <th>Инвентарный номер</th>
                <th>Серийный номер</th>
                <th>Название</th>
                <th>Описание</th>
                <th>Цена</th>
                <th>Количество</th>
                <th>Дата ввода в эксплуатацию</th>
                <th>Дата списания</th>
                <th>Фото</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $material_value): ?>
            <tr>
            <td><?php echo $material_value->getLocationName() ?></td>
            <td><?php echo $material_value->getTypeName() ?></td>
            <td><?php echo $material_value->getInventoryNum() ?></td>
            <td><?php echo $material_value->getSerialNum() ?></td>
            <td><?php echo $material_value->getName() ?></td>
            <td><?php echo $material_value->getDescription() ?></td>
            <td><?php echo $material_value->getPrice() ?></td>
            <td><?php echo $material_value->getCount() ?></td>
            <td><?php echo $material_value->getEnterDate() ?></td>
            <td><?php echo $material_value->getExitDate() ?></td>
            <td><?php echo $material_value->getPhoto() ?></td>            

                <td><?php echo $this->tag->linkTo(["material_value/edit/" . $material_value->getMaterialValueId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["material_value/delete/" . $material_value->getMaterialValueId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<!-- <div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("material_value/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("material_value/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("material_value/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("material_value/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div> -->
<div class="d-flex justify-content-center">
    <? echo CustomTags::pagination([
        'link' => 'material_value/search?page=%d',
        'current' => $page->current,
        'next' => $page->next,
        'before' => $page->before,
        'count'   => $page->total_pages,
    ]);
    ?>
</div>
