<? echo Phalcon\Tag::javascriptInclude('js/material_type.js'); ?>
<div class="row">
    <nav>
        <ul class="pager">
            <?php   echo $this->tag->linkTo(["material_value", '<i class="fas fa-arrow-left"></i><span class="font-weight-bold"> Вернуться</span>', 'class' => 'btn btn-success']);
                    $role=$this->session->auth['role'];
                    if($role == 'admin') {
                        echo $this->tag->linkTo(["material_value/qr/" . $material_value_id, 'Сгенерировать QR-код', 'class' => 'btn btn-info']);
                    }
            ?>
        </ul>
    </nav>
</div>
<div class="row">
    <div class="col-7">

        <div class="form-group required">
            <label for="fieldLocationLocationId" class="col-12 control-label">Местоположение</label>
            <div class="col-12">
                <? echo Phalcon\Tag::select(
                    [
                        'location_location_id',
                        Location::getAllByFullname(),
                        'using'      => [
                            'location_id',
                            'fullname',
                        ],
                        'useEmpty'   => true,
                        'emptyText'  => 'Выберите один из вариантов',
                        'emptyValue' => '@',
                        'class' => 'form-control',
                        'id' => 'fieldLocationLocationId',
                    ]
                );
                ?>
            </div>
        </div>

        <div class="form-group required">
            <label for="fieldType" class="col-12 control-label">Тип ценности</label>
            <div class="col-12">
                <? echo Phalcon\Tag::selectStatic(
                    [
                        'type',
                        MaterialValue::getAllTypes(),
                        'useEmpty'   => true,
                        'emptyText'  => 'Выберите один из вариантов',
                        'emptyValue' => '@',
                        'class' => 'form-control',
                        'id' => 'fieldType',
                    ]
                );
                ?>
            </div>
        </div>

        <div class="form-group">
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="fieldInventoryNum" class="col-12 control-label">Инвентарный номер</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["inventory_num", "size" => 30, "class" => "form-control", "id" => "fieldInventoryNum"]) ?>
                    </div>
                </div>
                <div class="form-group col-6">
                    <label for="fieldSerialNum" class="col-12 control-label">Серийный номер</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["serial_num", "size" => 30, "class" => "form-control", "id" => "fieldSerialNum"]) ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group required">
            <label for="fieldName" class="col-12 control-label">Название</label>
            <div class="col-12">
                <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
            </div>
        </div>

        <div class="form-group">
            <label for="fieldDescription" class="col-12 control-label">Описание</label>
            <div class="col-12">
                <?php echo $this->tag->textArea(["description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescription"]) ?>
            </div>
        </div>

        <div class="form-group">
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="fieldPrice" class="col-12 control-label">Цена</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
                    </div>
                </div>
                <div class="form-group col-6">
                    <label for="fieldCount" class="col-12 control-label">Количество</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["count", "type" => "number", "class" => "form-control", "id" => "fieldCount"]) ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="fieldEnterDate" class="col-12 control-label">Дата ввода в эксплуатацию</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["enter_date", "type" => "date", "class" => "form-control", "id" => "fieldEnterDate"]) ?>
                    </div>
                </div>
                <div class="form-group col-6">
                    <label for="fieldExitDate" class="col-12 control-label">Дата списания</label>
                    <div class="col-12">
                        <?php echo $this->tag->textField(["exit_date", "type" => "date", "class" => "form-control", "id" => "fieldExitDate"]) ?>
                    </div>
                </div>
            </div>
        </div>

        <? if (isset($photo)) { echo Phalcon\Tag::image(['files/photo/'.$photo, 'style' => 'max-height: 30vh;', 'class' => 'p-3']); }?>

    </div>
    <div class="col-5">
        <h4 id="furnitureLabel">Мебель</h4>
        <div class="form-group required" id="fieldFurnitureBlock">
            <label for="fieldFurnitureSpecification" class="col-12 control-label">Характеристики</label>
            <div class="col-12">
                <?php echo $this->tag->textArea(["furniture_specification", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldFurnitureSpecification"]) ?>
            </div>
        </div>
        <h4 id="equipmentLabel">Оргтехника</h4>
        <div class="form-group required" id="fieldEquipmentTypeBlock">
            <label for="fieldEquipmentType" class="col-12 control-label">Тип оргтехники</label>
            <div class="col-12">
                <?php echo $this->tag->textField(["equipment_type", "size" => 30, "class" => "form-control", "id" => "fieldEquipmentType"]) ?>
            </div>
        </div>

        <div class="form-group required" id="fieldEquipmentManufacturerBlock">
            <label for="fieldEquipmentManufacturer" class="col-12 control-label">Производитель</label>
            <div class="col-12">
                <?php echo $this->tag->textField(["equipment_manufacturer", "size" => 30, "class" => "form-control", "id" => "fieldEquipmentManufacturer"]) ?>
            </div>
        </div>
    </div>

    <div class="col-12" id="tables">
        <?php if (isset($licenses)): ?>
        <h4 class="col-12">Лицензии на ПО</h4>
        <div class="row px-3 col-12" id="licensesTable">
            <table class="table table-bordered table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col"><p class="text-center m-0">Название ПО</p></th>
                        <th scope="col"><p class="text-center m-0">Версия ПО</p></th>
                        <th scope="col"><p class="text-center m-0">Номер лицензии</p></th>
                        <th scope="col"><p class="text-center m-0">Дата окончания</p></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($licenses as $license): ?>
                    <tr>
                        <td><? echo nl2br($license->getPoName()) ?></td>
                        <td><? echo nl2br($license->getPoVersion()) ?></td>
                        <td><? echo nl2br($license->getLicenseNumber()) ?></td>
                        <td><? echo nl2br($license->getEndDate()) ?></td>
                    </tr>
                <? endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php endif; ?>
        <?php if (isset($specifications)): ?>
        <h4 class="col-12">Характеристики</h4>
        <div class="row px-3 col-12" id="specificationsTable">
            <table class="table table-bordered table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col"><p class="text-center m-0">Название характеристики</p></th>
                        <th scope="col"><p class="text-center m-0">Ожидаемое максимальное значение характеристики</p></th>
                        <th scope="col"><p class="text-center m-0">Текущее значение</p></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($specifications as $equip_has_spec): 
                        $specification = $equip_has_spec->Specification;
                    ?>
                    <tr>
                        <td><? echo nl2br($specification->getName()) ?></td>
                        <td><? echo nl2br($specification->getExpectedMaxValue()) ?></td>
                        <td><? echo nl2br($equip_has_spec->getCurrentValue()) ?></td>
                    </tr>
                <? endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php endif; ?>
    </div>
</div>

<script>
    $(function() {
        $(':input').each(function() {
            $(this).prop('readonly', true);
        });
        $('select').each(function() {
            $(this).attr('disabled', true);
        });
    });
</script>