<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Местоположения
    </h1>
</div>

<?php echo $this->getContent() ?>

<div class="d-flex justify-content-end py-3">
    <?php echo $this->tag->linkTo(["location/new", '<i class="fas fa-plus"></i><span class="font-weight-bold"> Добавить</span>', 'class' => 'btn btn-sm btn-success']) ?>
</div>

<?php
    echo $this->tag->form(
        [
            "location/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <div class="form-row">
        <div class="form-group col-5">
            <?php echo $this->tag->textField(["campus", "size" => 30, "class" => "form-control", "id" => "fieldCampus", "placeholder" => "Введите корпус"]) ?>
        </div>
        <div class="form-group col-5">
            <?php echo $this->tag->textField(["auditory", "size" => 30, "class" => "form-control", "id" => "fieldAuditory", "placeholder" => "Введите аудиторию"]) ?>
        </div>
        <div class="form-group col-2">
            <?php echo $this->tag->submitButton(["Найти", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<?php if (isset($page)) { 
    $this->partial("location/pagination", [ 'page' => $page ]);
}?>
