<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <?php echo $this->tag->linkTo(["location", '<i class="fas fa-arrow-left"></i><span class="font-weight-bold"> Вернуться</span>', 'class' => 'btn btn-success']) ?>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Добавить местоположение
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "location/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <div class="form-row">
        <div class="form-group col-6">
            <label for="fieldCampus" class="control-label">Корпус</label>
            <div class="col-12">
                <?php echo $this->tag->textField(["campus", "size" => 30, "class" => "form-control", "id" => "fieldCampus", "placeholder" => "Введите корпус"]) ?>
            </div>            
        </div>
        <div class="form-group col-6">
            <label for="fieldAuditory" class="control-label">Аудитория</label>
            <div class="col-12">
                <?php echo $this->tag->textField(["auditory", "size" => 30, "class" => "form-control", "id" => "fieldAuditory", "placeholder" => "Введите аудиторию"]) ?>
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    <div class="col-12">
        <?php echo $this->tag->submitButton(["Добавить", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
